name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
      - run: deno task check
      - run: deno task build
  publish:
    runs-on: ubuntu-latest
    needs: check
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          registry-url: https://registry.npmjs.org
      - uses: denoland/setup-deno@v2
      - run: deno task build
      - name: git push
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name 'github-actions[bot]'
            git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git diff
            git add .
            git commit -m 'ci: autogenerate files'
            git pull --rebase
            git push
          fi
      - run: deno task publish
